title: Serverless ML Course by Ilkka 
description: Live dashboards for the different Modules (just checking where this ends up)
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 
